"""create mood tracking table

Revision ID: 7ccb528afde7
Revises:
Create Date: 2026-04-05 16:02:24.730772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ccb528afde7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mood_track",
        sa.Column(
            "username",
            sa.String(),
            nullable=False,
            comment="Username of the entry author",
        ),
        sa.Column(
            "mood_entry", sa.String(), nullable=False, comment="Mood entry description"
        ),
        sa.Column(
            "mood_emoji",
            sa.String(),
            nullable=False,
            comment="Mood emoji representation",
        ),
        sa.Column("comment", sa.Text(), nullable=True, comment="Optional user comment"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of the entry creation",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__mood_track")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mood_track")
    # ### end Alembic commands ###
